# .github/workflows/ci.yml
name: CI
on: [push, pull_request]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 20, cache: npm }
      - name: Build WASM (Docker emscripten)
        run: |
          chmod +x scripts/build-wasm.emf.sh
          chmod +x scripts/build-wasm.wmf.sh
          npm run build:wasm
      - run: npm ci
      - run: npm run build
      - run: npm test
